name: DNSTwisting For TypoSquats

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "domain to check with DNS Twist"
        default: "google.com"
        required: true
        type: string

permissions:
  contents: read
  actions: write

jobs:
  DNSTwist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DNSTwist
        run: dnstwist "${{ github.event.inputs.domain }}"
