name: WPSScan
# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      domain:
        description: 'Domain To Scan'
        default: 'https://example.com'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  WPSScan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Set up environment
    - uses: actions/checkout@v4

    - name: Docker Pull
      run: docker pull wpscanteam/wpscan
      
    - name: Docker Run
      run: docker run wpscanteam/wpscan --url ${{ github.event.inputs.domain }} --ignore-main-redirect --random-user-agent
      
